# Generated by Django 5.2.3 on 2025-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="search_history",
            field=models.BooleanField(default=True),
        ),
    ]
