version: '3.8'  # 생략 가능하지만 명시 권장

services:
#  # --------------------------------------------
#  # 1) PostgreSQL DB
#  # --------------------------------------------
#  db:
#    image: seonhongmun/fixlog-db:prod-latest
#    env_file:
#      - .env.prod
#    ports:
#      - "5431:5432"
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    restart: always
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
  # --------------------------------------------
  # 2) Redis
  # --------------------------------------------
  redis:
    image: seonhongmun/fixlog-redis:prod-latest
    ports:
      - "6379:6379"
    restart: always

  # --------------------------------------------
  # 3) Daphne (ASGI: WebSocket 처리)
  # --------------------------------------------
  daphne:
    image: seonhongmun/fixlog-daphne:prod-latest
    command: >
      sh -c "./scripts/run_daphne.sh"
    env_file:
      - .env.prod   # DB 연결용 POSTGRES_* 를 .env 로 읽도록
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app/app
#    ports:
#      - "8000:8000"
    depends_on:
#      - db
      - redis
    restart: always

  # --------------------------------------------
  # 4) API (Gunicorn WSGI: HTTP 요청 처리)
  # --------------------------------------------
  api:
    image: seonhongmun/fixlog-api:prod-latest
    command: >
      sh -c "./scripts/run_api.sh"
    env_file:
      - .env.prod   # DB 연결용 POSTGRES_* 를 .env.prod 로 읽도록
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app/app
    ports:
      - "8000:8000"
    container_name: api
    depends_on:
#      - db
      - redis
    restart: always

  # --------------------------------------------
  # 5) Nginx (리버스 프록시 & 정적파일 서빙)
  # --------------------------------------------
  nginx:
    image: seonhongmun/fixlog-nginx:prod-latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    depends_on:
      - daphne
      - api
    restart: always

volumes:
  db_data: {}
  static_volume: {}