# Generated by Django 5.2.3 on 2025-07-20 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("util", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workroom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="작성일자")),
                ("name", models.CharField(max_length=255)),
                ("introduction", models.CharField(max_length=512)),
                ("start_date", models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ("end_date", models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ("description", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_workrooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "워크룸",
                "verbose_name_plural": "워크룸",
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="작성일자")),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "시작전"), ("in_progress", "진행중"), ("completed", "완료")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("due_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="issues", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "workroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="issues", to="workroom.workroom"
                    ),
                ),
            ],
            options={
                "verbose_name": "워크룸 이슈",
                "verbose_name_plural": "워크룸 이슈",
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="작성일자")),
                ("title", models.CharField(max_length=255)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("recurrence", models.JSONField(blank=True, default=dict, null=True)),
                ("color", models.CharField(default="#F74627", max_length=7)),
                ("alert", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True, null=True)),
                ("memo", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="workroom.workroom"
                    ),
                ),
            ],
            options={
                "verbose_name": "워크룸 일정",
                "verbose_name_plural": "워크룸 일정",
            },
        ),
        migrations.CreateModel(
            name="WorkroomDesign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("design", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="util.design")),
                (
                    "workroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workroom_designs",
                        to="workroom.workroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "워크룸-디자인",
                "verbose_name_plural": "워크룸-디자인",
                "unique_together": {("workroom", "design")},
            },
        ),
        migrations.AddField(
            model_name="workroom",
            name="designs",
            field=models.ManyToManyField(related_name="workrooms", through="workroom.WorkroomDesign", to="util.design"),
        ),
        migrations.CreateModel(
            name="WorkroomLanguage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="util.language")),
                (
                    "workroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workroom_languages",
                        to="workroom.workroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "워크룸-언어",
                "verbose_name_plural": "워크룸-언어",
                "unique_together": {("workroom", "language")},
            },
        ),
        migrations.AddField(
            model_name="workroom",
            name="languages",
            field=models.ManyToManyField(
                related_name="workrooms", through="workroom.WorkroomLanguage", to="util.language"
            ),
        ),
        migrations.CreateModel(
            name="WorkroomPosition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.PositiveIntegerField(default=1)),
                ("current_count", models.PositiveIntegerField(default=0)),
                ("position", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="util.position")),
                (
                    "workroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workroom_positions",
                        to="workroom.workroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "워크룸-포지션",
                "verbose_name_plural": "워크룸-포지션",
                "unique_together": {("workroom", "position")},
            },
        ),
        migrations.AddField(
            model_name="workroom",
            name="positions",
            field=models.ManyToManyField(
                related_name="workrooms", through="workroom.WorkroomPosition", to="util.position"
            ),
        ),
        migrations.CreateModel(
            name="WorkroomStack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stack", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="util.stack")),
                (
                    "workroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workroom_stacks",
                        to="workroom.workroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "워크룸-스택",
                "verbose_name_plural": "워크룸-스택",
                "unique_together": {("workroom", "stack")},
            },
        ),
        migrations.AddField(
            model_name="workroom",
            name="stacks",
            field=models.ManyToManyField(related_name="workrooms", through="workroom.WorkroomStack", to="util.stack"),
        ),
        migrations.CreateModel(
            name="WorkroomMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="작성일자")),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "총 관리자"), ("manager", "부관리자"), ("member", "일반 멤버")],
                        default="member",
                        max_length=10,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "보기만 가능"),
                            ("add_event", "일정 추가만 가능"),
                            ("modify_event", "일정 추가·삭제 가능"),
                            ("admin", "모든 권한"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "대기"), ("accepted", "승인"), ("rejected", "거절")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("position_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workroom_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="members", to="workroom.workroom"
                    ),
                ),
            ],
            options={
                "verbose_name": "워크룸-멤버",
                "verbose_name_plural": "워크룸-멤버",
                "unique_together": {("user", "workroom")},
            },
        ),
        migrations.CreateModel(
            name="WorkroomReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="작성일자")),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField()),
                (
                    "reviewee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="workroom.workroom"
                    ),
                ),
            ],
            options={
                "verbose_name": "워크룸 리뷰",
                "verbose_name_plural": "워크룸 리뷰",
                "unique_together": {("workroom", "reviewer", "reviewee")},
            },
        ),
    ]