# Generated by Django 5.2.3 on 2025-07-21 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("util", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("deadline", models.DateTimeField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_estimated_period", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("recruiting", "모집중"), ("completed", "모집완료")],
                        default="recruiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectLanguage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="util.language")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.project")),
            ],
            options={
                "db_table": "project_language",
                "unique_together": {("project", "language")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="languages",
            field=models.ManyToManyField(blank=True, through="crew.ProjectLanguage", to="util.language"),
        ),
        migrations.CreateModel(
            name="ProjectPosition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.IntegerField(default=1)),
                ("position", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="util.position")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.project")),
            ],
            options={
                "db_table": "project_position",
                "unique_together": {("project", "position")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="positions",
            field=models.ManyToManyField(blank=True, through="crew.ProjectPosition", to="util.position"),
        ),
        migrations.CreateModel(
            name="ProjectSkillTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.project")),
                ("skill_tool", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="util.stack")),
            ],
            options={
                "db_table": "project_skill_tool",
                "unique_together": {("project", "skill_tool")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="skill_tools",
            field=models.ManyToManyField(blank=True, through="crew.ProjectSkillTool", to="util.stack"),
        ),
    ]
