# Generated by Django 5.2.3 on 2025-08-18 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crew", "0001_initial"),
        ("util", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDesign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("design", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="util.design")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.project")),
            ],
            options={
                "db_table": "project_design",
                "unique_together": {("project", "design")},
            },
        ),
        migrations.CreateModel(
            name="ProjectCoopTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("coop_tool", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="util.cooptool")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.project")),
            ],
            options={
                "db_table": "project_coop_tool",
                "unique_together": {("project", "coop_tool")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="designs",
            field=models.ManyToManyField(blank=True, through="crew.ProjectDesign", to="util.design"),
        ),
        migrations.AddField(
            model_name="project",
            name="coop_tools",
            field=models.ManyToManyField(blank=True, through="crew.ProjectCoopTool", to="util.cooptool"),
        ),
    ]
