# Generated by Django 5.2.3 on 2025-07-06 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crew", "0001_initial"),
        ("util", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectLanguage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="util.language")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.project")),
            ],
            options={
                "db_table": "project_language",
                "unique_together": {("project", "language")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="languages",
            field=models.ManyToManyField(blank=True, through="crew.ProjectLanguage", to="util.language"),
        ),
        migrations.CreateModel(
            name="ProjectPosition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.IntegerField(default=1)),
                ("position", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="util.position")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.project")),
            ],
            options={
                "db_table": "project_position",
                "unique_together": {("project", "position")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="positions",
            field=models.ManyToManyField(blank=True, through="crew.ProjectPosition", to="util.position"),
        ),
        migrations.CreateModel(
            name="ProjectSkillTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.project")),
                ("skill_tool", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="util.stack")),
            ],
            options={
                "db_table": "project_skill_tool",
                "unique_together": {("project", "skill_tool")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="skill_tools",
            field=models.ManyToManyField(blank=True, through="crew.ProjectSkillTool", to="util.stack"),
        ),
    ]
