# Generated by Django 5.2.3 on 2025-06-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crew", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("recruiting", "모집중"), ("completed", "모집완료")], default="recruiting", max_length=20
            ),
        ),
    ]
