# Generated by Django 5.2.3 on 2025-07-28 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crew", "0001_initial"),
        ("util", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCoopTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("coop_tool", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="util.cooptool")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.project")),
            ],
            options={
                "db_table": "project_coop_tool",
                "unique_together": {("project", "coop_tool")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="coop_tools",
            field=models.ManyToManyField(blank=True, through="crew.ProjectCoopTool", to="util.cooptool"),
        ),
        migrations.CreateModel(
            name="ProjectDesign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("design", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="util.design")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.project")),
            ],
            options={
                "db_table": "project_design",
                "unique_together": {("project", "design")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="designs",
            field=models.ManyToManyField(blank=True, through="crew.ProjectDesign", to="util.design"),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="crew.project"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "application",
                "unique_together": {("user", "project")},
            },
        ),
    ]
