# Generated by Django 5.2.3 on 2025-07-27 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="작성일자")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("fixred", "픽레드"), ("crew", "크루모집"), ("workroom", "워크룸")], max_length=10
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apply", "지원"),
                            ("comment", "댓글"),
                            ("complete", "완료"),
                            ("deadline", "마감임박"),
                            ("feedback", "평가"),
                            ("follow", "팔로우"),
                            ("invite", "초대"),
                            ("like", "좋아요"),
                            ("mention", "언급"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
