# Generated by Django 5.2.3 on 2025-07-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="content",
        ),
    ]
