worker_processes 1;

events {
  worker_connections 1024;
}

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile        on;

  # 성능 향상을 위한 gzip 압축 활성화
  gzip on;
  gzip_types text/plain application/json application/javascript text/css application/xml text/javascript;

  # WebSocket 백엔드 (Daphne)
upstream daphne_ws {
    server fixlog_back-daphne-1:8000;
}

upstream gunicorn_api {
    server fixlog_back-api-1:8000;
}


  server {
    listen 80;
    server_name api.fixlog.co.kr;
    # 클라이언트 연결을 위한 keep-alive 타임아웃 설정
    keepalive_timeout 65;

    # Nginx를 통해 정적 파일 직접 제공 (s3에 스태틱 파일이 올라가 있기 때문에 주석처리)
#     location /static/ {
#       alias /app/static/;
#       access_log off;
#     }

    # WebSocket 요청은 Daphne가 처리
    location /ws/ {
      proxy_pass http://daphne_ws;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_read_timeout 300;  # 장시간 연결되는 WS 요청의 타임아웃 방지
    }

    # API 요청은 Gunicorn이 처리
    location /api/ {
      proxy_pass http://gunicorn_api;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # 기타 모든 요청 처리 (선택사항)
    location / {
      proxy_pass http://gunicorn_api;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}