# Generated by Django 5.2.3 on 2025-07-03 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fixred",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="작성일자")),
                ("updated_At", models.DateTimeField(auto_now=True, verbose_name="수정일자")),
                ("content", models.TextField()),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                (
                    "read_permission",
                    models.CharField(
                        choices=[
                            ("all", "모든 사람"),
                            ("follow", "내가 팔로우 하는 사람만"),
                            ("mention", "멘션한 사람만"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fixreds", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "fixred",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FixredComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="작성일자")),
                ("comment", models.CharField(max_length=500)),
                (
                    "fixred",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="fixred.fixred"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FixredImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="fixred_images/", verbose_name="fixred_image")),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fixred.fixred")),
            ],
        ),
        migrations.CreateModel(
            name="FixredReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="작성일자")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("abuse", "욕설/비하"),
                            ("privacy", "개인정보 노출"),
                            ("inappropriate", "부적절한 내용"),
                            ("illegal", "불법/범죄"),
                            ("etc", "기타"),
                        ],
                        max_length=100,
                    ),
                ),
                ("fixred_post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fixred.fixred")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FixredBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="작성일자")),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixred_blocks_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixred_blocks_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fixred_block",
                "unique_together": {("blocker", "blocked")},
            },
        ),
    ]
