# Generated by Django 5.2.3 on 2025-07-03 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixred", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fixredblock",
            options={"verbose_name": "픽레드 차단", "verbose_name_plural": "픽레드 차단 목록"},
        ),
        migrations.AlterField(
            model_name="fixredblock",
            name="blocked",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fixred_blocks_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="차단 대상",
            ),
        ),
        migrations.AlterField(
            model_name="fixredblock",
            name="blocker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fixred_blocks_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="차단자",
            ),
        ),
    ]
