# Generated by Django 5.2.3 on 2025-07-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixred", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fixred",
            old_name="updated_At",
            new_name="updated_at",
        ),
    ]
