# Generated by Django 5.2.3 on 2025-07-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixred", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixredcomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="수정일자"),
        ),
        migrations.AlterField(
            model_name="fixredimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="images", to="fixred.fixred"
            ),
        ),
    ]
