# Generated by Django 5.2.3 on 2025-08-18 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixred", "0002_alter_fixredimage_post_fixredlike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fixred",
            name="mentioned_users",
            field=models.ManyToManyField(
                blank=True, related_name="mention_in_fixreds", to=settings.AUTH_USER_MODEL, verbose_name="언급된 사용자"
            ),
        ),
        migrations.AlterField(
            model_name="fixred",
            name="read_permission",
            field=models.CharField(
                choices=[
                    ("public", "모든 사람"),
                    ("follower", "나를 팔로우 하는 사람만"),
                    ("mention", "멘션한 사람만"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]


# Generated by Django 5.2.3 on 2025-08-17 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixred", "0002_alter_fixredimage_post_fixredlike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fixred",
            name="mentioned_users",
            field=models.ManyToManyField(
                blank=True, related_name="mention_in_fixreds", to=settings.AUTH_USER_MODEL, verbose_name="언급된 사용자"
            ),
        ),
        migrations.AlterField(
            model_name="fixred",
            name="read_permission",
            field=models.CharField(
                choices=[
                    ("public", "모든 사람"),
                    ("follower", "나를 팔로우 하는 사람만"),
                    ("mention", "멘션한 사람만"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
