# Generated by Django 5.2.3 on 2025-07-26 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixred", "0002_fixredcomment_updated_at_alter_fixredimage_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixredimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="fixredimage_set", to="fixred.fixred"
            ),
        ),
    ]
