# Generated by Django 5.2.3 on 2025-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixred", "0003_fixred_mentioned_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixred",
            name="read_permission",
            field=models.CharField(
                choices=[
                    ("public", "모든 사람"),
                    ("follower", "나를 팔로우 하는 사람만"),
                    ("mention", "멘션한 사람만"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
