# Generated by Django 5.2.3 on 2025-07-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixletter",
            name="last_message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="last_fixletters",
                to="fixletter.message",
            ),
        ),
    ]
