# Generated by Django 5.2.3 on 2025-08-17 12:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixletter", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="fixletterblock",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="fixletter",
            name="last_message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_fixletters",
                to="fixletter.message",
            ),
        ),
        migrations.AlterField(
            model_name="fixletter",
            name="last_sent_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="message",
            name="send_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="messages_sent", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["fixletter", "sent_at"], name="fixletter_m_fixlett_fb68a5_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["fixletter", "is_read", "sent_at"], name="fixletter_m_fixlett_f1f2c0_idx"),
        ),
        migrations.AddConstraint(
            model_name="fixletter",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_user_id__lt", models.F("to_user_id"))), name="fixletter_from_lt_to"
            ),
        ),
        migrations.AddConstraint(
            model_name="fixletter",
            constraint=models.UniqueConstraint(fields=("from_user", "to_user"), name="fixletter_unique_pair"),
        ),
        migrations.AddConstraint(
            model_name="fixletterblock",
            constraint=models.UniqueConstraint(fields=("blocker", "blocked"), name="uniq_fixletter_block_pair"),
        ),
        migrations.AlterModelTable(
            name="message",
            table=None,
        ),
    ]
